# Generated by Django 4.2.20 on 2026-04-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_competition_admin',
            field=models.BooleanField(default=False),
        ),
    ]
