# Generated by Django 4.2.1 on 2024-01-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('modality', models.CharField(choices=[('G', 'Gymnastics'), ('M', 'Monostructural'), ('W', 'Weightlifting')], max_length=2)),
                ('type', models.CharField(choices=[('ST', 'Strength'), ('CA', 'Cardio'), ('PL', 'Plyometrics'), ('OL', 'Olympic Lifting'), ('PO', 'Power Lifting'), ('SM', 'Strongman'), ('OT', 'Other'), ('SC', 'Stretching')], max_length=2)),
                ('body_part', models.CharField(max_length=50)),
                ('equipment', models.CharField(max_length=50)),
            ],
        ),
    ]
