# Generated by Django 4.2.20 on 2026-02-22 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0001_initial'),
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='athlete',
        ),
        migrations.RemoveField(
            model_name='score',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='score',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='is_scaled',
        ),
        migrations.AddField(
            model_name='score',
            name='is_scaled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('S', 'Submitted'), ('P', 'Processing'), ('E', 'Error'), ('A', 'Approved'), ('R', 'Rejected')], default='S', max_length=2)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athlete.athlete')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='athlete.competition')),
                ('score', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.score')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workout')),
            ],
        ),
    ]
