# Generated by Django 4.2.1 on 2024-01-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_rename_movements_movement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='body_part',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movement',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='movement',
            name='equipment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movement',
            name='modality',
            field=models.CharField(blank=True, choices=[('G', 'Gymnastics'), ('M', 'Monostructural'), ('W', 'Weightlifting')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='movement',
            name='type',
            field=models.CharField(blank=True, choices=[('ST', 'Strength'), ('CA', 'Cardio'), ('PL', 'Plyometrics'), ('OL', 'Olympic Lifting'), ('PO', 'Power Lifting'), ('SM', 'Strongman'), ('OT', 'Other'), ('SC', 'Stretching')], max_length=2, null=True),
        ),
    ]
