# Generated by Django 4.2.20 on 2026-02-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_alter_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='urlPath',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
