# Generated by Django 4.2.1 on 2024-01-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_alter_movement_body_part_alter_movement_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
