# Generated by Django 4.2.1 on 2024-01-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_alter_movement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
