# Generated by Django 4.2.20 on 2026-03-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_video_urlpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='movement_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='score',
            name='status',
            field=models.CharField(blank=True, choices=[('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], max_length=20, null=True),
        ),
    ]
