# Generated by Django 4.2.1 on 2024-01-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_alter_movement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='name',
            field=models.CharField(max_length=75),
        ),
    ]
