# Generated by Django 4.2.20 on 2026-03-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_add_score_status_and_movement_breakdown'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutcomponent',
            options={'ordering': ['round', 'sequence']},
        ),
        migrations.AddField(
            model_name='workoutcomponent',
            name='round',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workoutcomponent',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='workoutcomponent',
            unique_together={('workout', 'round', 'sequence')},
        ),
    ]
