# Generated by Django 4.2.20 on 2026-04-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_add_round_to_workout_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
