# Generated by Django 4.2.20 on 2026-04-11 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_alter_score_is_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_good_rep', models.BooleanField(default=False)),
                ('no_rep_reason', models.CharField(choices=[('D', 'Did not reach full depth'), ('E', 'Did not reach full extension'), ('T', 'Did not hit target')], max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rep_number', models.IntegerField(blank=True, null=True)),
                ('rep_timestamp', models.IntegerField(blank=True, help_text='seconds at which the rep occurred', null=True)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workout.movement')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.score')),
            ],
        ),
    ]
