# Generated by Django 4.2.20 on 2026-05-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_scorebreakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorebreakdown',
            name='no_rep_reason',
            field=models.CharField(choices=[('D', 'Did not reach full depth'), ('E', 'Did not reach full extension'), ('T', 'Did not hit target'), ('Q', 'Equipment not in hands')], max_length=2, null=True),
        ),
    ]
