# Generated by Django 4.2.20 on 2026-05-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0009_add_equipment_no_rep_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='good_reps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
