# Generated by Django 4.2.20 on 2026-06-18 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0001_initial'),
        ('workout', '0010_score_good_reps'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='athlete.competition'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
