# Generated by Django 4.2.1 on 2024-01-17 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Affiliate',
                'verbose_name_plural': 'Affiliates',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('code', models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='ISO Code')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('code', models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='ISO Code')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2)),
                ('date_of_birth', models.DateField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('email', models.EmailField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('profile_photo', models.ImageField(upload_to='static/images/')),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='athlete.affiliate')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='athlete.country')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='athlete.region')),
            ],
            options={
                'verbose_name': 'Athlete',
                'verbose_name_plural': 'Athletes',
            },
        ),
        migrations.AddField(
            model_name='affiliate',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='athlete.country'),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='athlete.region'),
        ),
    ]
