# Generated by Django 4.2.1 on 2024-02-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0002_remove_affiliate_region_remove_athlete_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='router_code',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Router Code'),
        ),
    ]
