# Generated by Django 4.2.1 on 2024-02-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0004_alter_affiliate_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
