# Generated by Django 4.2.20 on 2025-11-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0007_alter_athlete_affiliate_alter_athlete_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2, null=True),
        ),
    ]
